### ISSUE TITLE
Wow, well done! And a query re sounds.

### ISSUE THREAD

**Issue by ricketyboo** [derHeinz/divoom-adapter#2]
First off, thanks for the work on this. I got one of these for Christmas and was trying to sniff it with android logs and wireshark but couldn't work out how to actually connect to the thing as I have almost 0 experience with bluetooth. Your library is very informative, I might have to dust this thing off and try again.

Secondly; have you had any luck, or thoughts, on getting the speaker component to work? Is bluepy capable of opening a connection to the speaker in audio output mode, or is case of  Bluetooth 4 can run as BLE or Classic, and audio is limited to classic?

**Comment by derHeinz** [comment]
Thank you.

AFAIK the speaker component is a classical BT function so you are able to 'stream' audio to it in using the classic bluetooth functions with were available in BT 3.0 or earlier (don't recognize excactly).
These are usually supported by any BT dongles and any OS like win or linux. Thus i think bluepy is not capable of streaming because it is a BT 4.0 (protoclls like GATT) implementation also known as 'Low Energy' or 'Smart'. To the best of my knowledge you would need to use another program that connects to the BT 3.0 audio device or another python library that is capable of classic bluetooth (protocoll may be A2DP).
